// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ygo-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YGOResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YGOResource) Reset() {
	*x = YGOResource{}
	mi := &file_ygo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YGOResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YGOResource) ProtoMessage() {}

func (x *YGOResource) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YGOResource.ProtoReflect.Descriptor instead.
func (*YGOResource) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{0}
}

func (x *YGOResource) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type YGOResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            []string               `protobuf:"bytes,1,rep,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YGOResources) Reset() {
	*x = YGOResources{}
	mi := &file_ygo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YGOResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YGOResources) ProtoMessage() {}

func (x *YGOResources) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YGOResources.ProtoReflect.Descriptor instead.
func (*YGOResources) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{1}
}

func (x *YGOResources) GetID() []string {
	if x != nil {
		return x.ID
	}
	return nil
}

type YGOCard struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ID            string                  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Color         string                  `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attribute     string                  `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Effect        string                  `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	MonsterType   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=monsterType,proto3" json:"monsterType,omitempty"`
	Attack        *wrapperspb.UInt32Value `protobuf:"bytes,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=defense,proto3" json:"defense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YGOCard) Reset() {
	*x = YGOCard{}
	mi := &file_ygo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YGOCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YGOCard) ProtoMessage() {}

func (x *YGOCard) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YGOCard.ProtoReflect.Descriptor instead.
func (*YGOCard) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{2}
}

func (x *YGOCard) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *YGOCard) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *YGOCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YGOCard) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *YGOCard) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *YGOCard) GetMonsterType() *wrapperspb.StringValue {
	if x != nil {
		return x.MonsterType
	}
	return nil
}

func (x *YGOCard) GetAttack() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Attack
	}
	return nil
}

func (x *YGOCard) GetDefense() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Defense
	}
	return nil
}

type YGOCards struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cards            []*YGOCard             `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	UnknownResources []string               `protobuf:"bytes,2,rep,name=unknownResources,proto3" json:"unknownResources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *YGOCards) Reset() {
	*x = YGOCards{}
	mi := &file_ygo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YGOCards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YGOCards) ProtoMessage() {}

func (x *YGOCards) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YGOCards.ProtoReflect.Descriptor instead.
func (*YGOCards) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{3}
}

func (x *YGOCards) GetCards() []*YGOCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *YGOCards) GetUnknownResources() []string {
	if x != nil {
		return x.UnknownResources
	}
	return nil
}

var File_ygo_service_proto protoreflect.FileDescriptor

const file_ygo_service_proto_rawDesc = "" +
	"\n" +
	"\x11ygo-service.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\"\x1d\n" +
	"\vYGOResource\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x1e\n" +
	"\fYGOResources\x12\x0e\n" +
	"\x02ID\x18\x01 \x03(\tR\x02ID\"\xa7\x02\n" +
	"\aYGOCard\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tattribute\x18\x04 \x01(\tR\tattribute\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\x12>\n" +
	"\vmonsterType\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vmonsterType\x124\n" +
	"\x06attack\x18\a \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06attack\x126\n" +
	"\adefense\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\adefense\"Y\n" +
	"\bYGOCards\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.pb.YGOCardR\x05cards\x12*\n" +
	"\x10unknownResources\x18\x02 \x03(\tR\x10unknownResources2f\n" +
	"\vCardService\x12)\n" +
	"\tQueryCard\x12\x0f.pb.YGOResource\x1a\v.pb.YGOCard\x12,\n" +
	"\n" +
	"QueryCards\x12\x10.pb.YGOResources\x1a\f.pb.YGOCardsB\x05Z\x03/pbb\x06proto3"

var (
	file_ygo_service_proto_rawDescOnce sync.Once
	file_ygo_service_proto_rawDescData []byte
)

func file_ygo_service_proto_rawDescGZIP() []byte {
	file_ygo_service_proto_rawDescOnce.Do(func() {
		file_ygo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)))
	})
	return file_ygo_service_proto_rawDescData
}

var file_ygo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ygo_service_proto_goTypes = []any{
	(*YGOResource)(nil),            // 0: pb.YGOResource
	(*YGOResources)(nil),           // 1: pb.YGOResources
	(*YGOCard)(nil),                // 2: pb.YGOCard
	(*YGOCards)(nil),               // 3: pb.YGOCards
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*wrapperspb.UInt32Value)(nil), // 5: google.protobuf.UInt32Value
}
var file_ygo_service_proto_depIdxs = []int32{
	4, // 0: pb.YGOCard.monsterType:type_name -> google.protobuf.StringValue
	5, // 1: pb.YGOCard.attack:type_name -> google.protobuf.UInt32Value
	5, // 2: pb.YGOCard.defense:type_name -> google.protobuf.UInt32Value
	2, // 3: pb.YGOCards.cards:type_name -> pb.YGOCard
	0, // 4: pb.CardService.QueryCard:input_type -> pb.YGOResource
	1, // 5: pb.CardService.QueryCards:input_type -> pb.YGOResources
	2, // 6: pb.CardService.QueryCard:output_type -> pb.YGOCard
	3, // 7: pb.CardService.QueryCards:output_type -> pb.YGOCards
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ygo_service_proto_init() }
func file_ygo_service_proto_init() {
	if File_ygo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ygo_service_proto_goTypes,
		DependencyIndexes: file_ygo_service_proto_depIdxs,
		MessageInfos:      file_ygo_service_proto_msgTypes,
	}.Build()
	File_ygo_service_proto = out.File
	file_ygo_service_proto_goTypes = nil
	file_ygo_service_proto_depIdxs = nil
}
