syntax = "proto3";

option go_package = "/ygo";
package ygo;

message ResourceID {
  string id = 1;
}

message ResourceIDs {
  repeated string ids = 1;
}

message ResourceName{
  string value = 1;
}

message ResourceNames {
  repeated string names = 1;
}

message SearchTerm {
  string id = 1;
  string name = 2;
}

message Archetype {
	string name = 1;
}

message BlackListed {
  repeated string black_listed_refs = 1;
}

message EffectiveTimeline {
  repeated string all_dates = 1;
  repeated string future_dates = 2;
  string active_date = 3;
}

enum CardRestrictionSortOrder {
  CARD_COLOR_ASC_CARD_NAME_ASC = 0;
  SCORE_DESC_CARD_COLOR_ASC_CARD_NAME_ASC = 1;
}
