syntax = "proto3";

option go_package = "/ygo";
package ygo;

import "common.proto";

service CardService {
  rpc GetCardColors(GetCardColorsRequest) returns (GetCardColorsResponse);

  rpc GetCardByID(GetCardByIDRequest) returns (GetCardByIDResponse);
  rpc GetCardsByID(GetCardsByIDRequest) returns (GetCardsByIDResponse);

  rpc GetCardsByName(GetCardsByNameRequest) returns (GetCardsByNameResponse);

  rpc GetCardsReferencingNameInEffect(GetCardsReferencingNameInEffectRequest) returns (GetCardsReferencingNameInEffectResponse);

  rpc GetArchetypalCardsUsingCardName(GetArchetypalCardsUsingCardNameRequest) returns (GetArchetypalCardsUsingCardNameResponse);
  rpc GetExplicitArchetypalInclusions(GetExplicitArchetypalInclusionsRequest) returns (GetExplicitArchetypalInclusionsResponse);
  rpc GetExplicitArchetypalExclusions(GetExplicitArchetypalExclusionsRequest) returns (GetExplicitArchetypalExclusionsResponse);

  rpc GetRandomCard(GetRandomCardRequest) returns (GetRandomCardResponse);
}

message GetCardColorsRequest {}

message GetCardColorsResponse {
  map<string, uint32> values = 1;
}

message GetCardByIDRequest {
    ygo.ResourceID subject = 1;
}

message GetCardByIDResponse {
    ygo.Card card = 1;
}

message GetCardsByIDRequest {
    ygo.ResourceIDs subjects = 1;
}

message GetCardsByIDResponse {
    Cards cards = 1;
}

message GetCardsByNameRequest {
    ygo.ResourceNames subjects = 1;
}

message GetCardsByNameResponse {
    ygo.Cards cards = 1;
}

message GetCardsReferencingNameInEffectRequest {
    ygo.ResourceNames subjects = 1;
}

message GetCardsReferencingNameInEffectResponse {
    repeated ygo.Card cards = 1;
}

message GetArchetypalCardsUsingCardNameRequest {
    ygo.Archetype subject = 1;
}

message GetArchetypalCardsUsingCardNameResponse {
    repeated ygo.Card cards = 1;
}

message GetExplicitArchetypalInclusionsRequest {
    ygo.Archetype subject = 1;
}

message GetExplicitArchetypalInclusionsResponse {
    repeated ygo.Card cards = 1;
}

message GetExplicitArchetypalExclusionsRequest {
    ygo.Archetype subject = 1;
}

message GetExplicitArchetypalExclusionsResponse {
    repeated ygo.Card cards = 1;
}

message GetRandomCardRequest {
    ygo.BlackListed blacklist = 1;
}

message GetRandomCardResponse {
    ygo.Card card = 1;
}

service ProductService {
	rpc GetCardsByProductID(GetCardsByProductIDRequest) returns (GetCardsByProductIDResponse);

	rpc GetProductSummaryByID(GetProductSummaryByIDRequest) returns (GetProductSummaryByIDResponse);
	rpc GetProductsSummaryByID(GetProductsSummaryByIDRequest) returns (GetProductsSummaryByIDResponse);

	rpc GetProductsReleasedSameDay(GetProductsReleasedSameDayRequest) returns (GetProductsReleasedSameDayResponse);
}

message GetCardsByProductIDRequest {
    ygo.ResourceID subject = 1;
}

message GetCardsByProductIDResponse {
    ygo.Product product = 1;
}

message GetProductSummaryByIDRequest {
    ygo.ResourceID subject = 1;
}

message GetProductSummaryByIDResponse {
    ygo.ProductSummary product_summary = 1;
}

message GetProductsSummaryByIDRequest {
    ygo.ResourceIDs subjects = 1;
}

message GetProductsSummaryByIDResponse {
    ygo.Products products = 1;
}

message GetProductsReleasedSameDayRequest {
    string date = 1;
}

message GetProductsReleasedSameDayResponse {
    repeated ProductSummary product = 1;
}

service CardRestrictionService {
	rpc GetEffectiveTimelineForFormat(Format) returns (ygo.EffectiveTimeline);
}

service ScoreService {
	rpc GetScoresByFormatAndDate(RestrictedContentRequest) returns (ScoresForFormatAndDate);

	rpc GetCardScoreByID(ygo.ResourceID) returns (CardScore);
  	rpc GetCardScoresByIDs(GetCardScoresByIDsRequest) returns (GetCardScoresByIDsResponse);
}

message GetCardScoresByIDsRequest {
    ygo.ResourceIDs subjects = 1;
}

message GetCardScoresByIDsResponse {
    ygo.CardScores scores = 1;
}
