// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ygo-service.proto

package ygo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_ygo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IDs           []string               `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_ygo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetIDs() []string {
	if x != nil {
		return x.IDs
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ID            string                  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Color         string                  `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attribute     string                  `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Effect        string                  `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	MonsterType   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=monsterType,proto3" json:"monsterType,omitempty"`
	Attack        *wrapperspb.UInt32Value `protobuf:"bytes,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=defense,proto3" json:"defense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ygo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Card) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Card) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *Card) GetMonsterType() *wrapperspb.StringValue {
	if x != nil {
		return x.MonsterType
	}
	return nil
}

func (x *Card) GetAttack() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Attack
	}
	return nil
}

func (x *Card) GetDefense() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Defense
	}
	return nil
}

type Cards struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cards            []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	UnknownResources []string               `protobuf:"bytes,2,rep,name=unknownResources,proto3" json:"unknownResources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cards) Reset() {
	*x = Cards{}
	mi := &file_ygo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cards) ProtoMessage() {}

func (x *Cards) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cards.ProtoReflect.Descriptor instead.
func (*Cards) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{3}
}

func (x *Cards) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Cards) GetUnknownResources() []string {
	if x != nil {
		return x.UnknownResources
	}
	return nil
}

var File_ygo_service_proto protoreflect.FileDescriptor

const file_ygo_service_proto_rawDesc = "" +
	"\n" +
	"\x11ygo-service.proto\x12\x03ygo\x1a\x1egoogle/protobuf/wrappers.proto\"\x1a\n" +
	"\bResource\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x1d\n" +
	"\tResources\x12\x10\n" +
	"\x03IDs\x18\x01 \x03(\tR\x03IDs\"\xa4\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tattribute\x18\x04 \x01(\tR\tattribute\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\x12>\n" +
	"\vmonsterType\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vmonsterType\x124\n" +
	"\x06attack\x18\a \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06attack\x126\n" +
	"\adefense\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\adefense\"T\n" +
	"\x05Cards\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\x12*\n" +
	"\x10unknownResources\x18\x02 \x03(\tR\x10unknownResources2^\n" +
	"\vCardService\x12%\n" +
	"\tQueryCard\x12\r.ygo.Resource\x1a\t.ygo.Card\x12(\n" +
	"\n" +
	"QueryCards\x12\x0e.ygo.Resources\x1a\n" +
	".ygo.CardsB\x06Z\x04/ygob\x06proto3"

var (
	file_ygo_service_proto_rawDescOnce sync.Once
	file_ygo_service_proto_rawDescData []byte
)

func file_ygo_service_proto_rawDescGZIP() []byte {
	file_ygo_service_proto_rawDescOnce.Do(func() {
		file_ygo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)))
	})
	return file_ygo_service_proto_rawDescData
}

var file_ygo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ygo_service_proto_goTypes = []any{
	(*Resource)(nil),               // 0: ygo.Resource
	(*Resources)(nil),              // 1: ygo.Resources
	(*Card)(nil),                   // 2: ygo.Card
	(*Cards)(nil),                  // 3: ygo.Cards
	(*wrapperspb.StringValue)(nil), // 4: google.protobuf.StringValue
	(*wrapperspb.UInt32Value)(nil), // 5: google.protobuf.UInt32Value
}
var file_ygo_service_proto_depIdxs = []int32{
	4, // 0: ygo.Card.monsterType:type_name -> google.protobuf.StringValue
	5, // 1: ygo.Card.attack:type_name -> google.protobuf.UInt32Value
	5, // 2: ygo.Card.defense:type_name -> google.protobuf.UInt32Value
	2, // 3: ygo.Cards.cards:type_name -> ygo.Card
	0, // 4: ygo.CardService.QueryCard:input_type -> ygo.Resource
	1, // 5: ygo.CardService.QueryCards:input_type -> ygo.Resources
	2, // 6: ygo.CardService.QueryCard:output_type -> ygo.Card
	3, // 7: ygo.CardService.QueryCards:output_type -> ygo.Cards
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ygo_service_proto_init() }
func file_ygo_service_proto_init() {
	if File_ygo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ygo_service_proto_goTypes,
		DependencyIndexes: file_ygo_service_proto_depIdxs,
		MessageInfos:      file_ygo_service_proto_msgTypes,
	}.Build()
	File_ygo_service_proto = out.File
	file_ygo_service_proto_goTypes = nil
	file_ygo_service_proto_depIdxs = nil
}
