// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ygo_service.proto

package ygo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardColors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]uint32      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardColors) Reset() {
	*x = CardColors{}
	mi := &file_ygo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardColors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardColors) ProtoMessage() {}

func (x *CardColors) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardColors.ProtoReflect.Descriptor instead.
func (*CardColors) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{0}
}

func (x *CardColors) GetValues() map[string]uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ResourceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceID) Reset() {
	*x = ResourceID{}
	mi := &file_ygo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceID) ProtoMessage() {}

func (x *ResourceID) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceID.ProtoReflect.Descriptor instead.
func (*ResourceID) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ResourceIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IDs           []string               `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceIDs) Reset() {
	*x = ResourceIDs{}
	mi := &file_ygo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIDs) ProtoMessage() {}

func (x *ResourceIDs) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIDs.ProtoReflect.Descriptor instead.
func (*ResourceIDs) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceIDs) GetIDs() []string {
	if x != nil {
		return x.IDs
	}
	return nil
}

type ResourceNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceNames) Reset() {
	*x = ResourceNames{}
	mi := &file_ygo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceNames) ProtoMessage() {}

func (x *ResourceNames) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceNames.ProtoReflect.Descriptor instead.
func (*ResourceNames) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SearchTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTerm) Reset() {
	*x = SearchTerm{}
	mi := &file_ygo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTerm) ProtoMessage() {}

func (x *SearchTerm) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTerm.ProtoReflect.Descriptor instead.
func (*SearchTerm) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTerm) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SearchTerm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Archetype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Archetype     string                 `protobuf:"bytes,1,opt,name=archetype,proto3" json:"archetype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Archetype) Reset() {
	*x = Archetype{}
	mi := &file_ygo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Archetype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Archetype) ProtoMessage() {}

func (x *Archetype) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Archetype.ProtoReflect.Descriptor instead.
func (*Archetype) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{5}
}

func (x *Archetype) GetArchetype() string {
	if x != nil {
		return x.Archetype
	}
	return ""
}

type BlackListed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlackListedRefs []string               `protobuf:"bytes,1,rep,name=black_listed_refs,json=blackListedRefs,proto3" json:"black_listed_refs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlackListed) Reset() {
	*x = BlackListed{}
	mi := &file_ygo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackListed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListed) ProtoMessage() {}

func (x *BlackListed) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListed.ProtoReflect.Descriptor instead.
func (*BlackListed) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{6}
}

func (x *BlackListed) GetBlackListedRefs() []string {
	if x != nil {
		return x.BlackListedRefs
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ID            string                  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Color         string                  `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Attribute     string                  `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Effect        string                  `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	MonsterType   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=monster_type,json=monsterType,proto3" json:"monster_type,omitempty"`
	Attack        *wrapperspb.UInt32Value `protobuf:"bytes,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=defense,proto3" json:"defense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ygo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{7}
}

func (x *Card) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Card) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Card) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *Card) GetMonsterType() *wrapperspb.StringValue {
	if x != nil {
		return x.MonsterType
	}
	return nil
}

func (x *Card) GetAttack() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Attack
	}
	return nil
}

func (x *Card) GetDefense() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Defense
	}
	return nil
}

type Cards struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardInfo         map[string]*Card       `protobuf:"bytes,1,rep,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnknownResources []string               `protobuf:"bytes,2,rep,name=unknown_resources,json=unknownResources,proto3" json:"unknown_resources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cards) Reset() {
	*x = Cards{}
	mi := &file_ygo_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cards) ProtoMessage() {}

func (x *Cards) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cards.ProtoReflect.Descriptor instead.
func (*Cards) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{8}
}

func (x *Cards) GetCardInfo() map[string]*Card {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

func (x *Cards) GetUnknownResources() []string {
	if x != nil {
		return x.UnknownResources
	}
	return nil
}

type CardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardList) Reset() {
	*x = CardList{}
	mi := &file_ygo_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{9}
}

func (x *CardList) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type Product struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ID                 string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Locale             string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	SubType            string                 `protobuf:"bytes,5,opt,name=subType,proto3" json:"subType,omitempty"`
	ReleaseDate        string                 `protobuf:"bytes,6,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	TotalItems         uint32                 `protobuf:"varint,7,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	Items              []*ProductItem         `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	RarityDistribution map[string]uint32      `protobuf:"bytes,9,rep,name=rarityDistribution,proto3" json:"rarityDistribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_ygo_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{10}
}

func (x *Product) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Product) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Product) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *Product) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Product) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Product) GetItems() []*ProductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Product) GetRarityDistribution() map[string]uint32 {
	if x != nil {
		return x.RarityDistribution
	}
	return nil
}

type ProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rarities      []string               `protobuf:"bytes,3,rep,name=rarities,proto3" json:"rarities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_ygo_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{11}
}

func (x *ProductItem) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *ProductItem) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ProductItem) GetRarities() []string {
	if x != nil {
		return x.Rarities
	}
	return nil
}

type ProductSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	SubType       string                 `protobuf:"bytes,5,opt,name=subType,proto3" json:"subType,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,6,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	TotalItems    uint32                 `protobuf:"varint,7,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSummary) Reset() {
	*x = ProductSummary{}
	mi := &file_ygo_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSummary) ProtoMessage() {}

func (x *ProductSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSummary.ProtoReflect.Descriptor instead.
func (*ProductSummary) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{12}
}

func (x *ProductSummary) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ProductSummary) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *ProductSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductSummary) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *ProductSummary) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *ProductSummary) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type Products struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Products         map[string]*ProductSummary `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnknownResources []string                   `protobuf:"bytes,2,rep,name=unknown_resources,json=unknownResources,proto3" json:"unknown_resources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Products) Reset() {
	*x = Products{}
	mi := &file_ygo_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{13}
}

func (x *Products) GetProducts() map[string]*ProductSummary {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Products) GetUnknownResources() []string {
	if x != nil {
		return x.UnknownResources
	}
	return nil
}

type CardScore struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CurrentScoreByFormat      map[string]uint32      `protobuf:"bytes,1,rep,name=currentScoreByFormat,proto3" json:"currentScoreByFormat,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	UniqueFormats             []string               `protobuf:"bytes,2,rep,name=uniqueFormats,proto3" json:"uniqueFormats,omitempty"`
	ScoreHistory              []*ScoreInstance       `protobuf:"bytes,3,rep,name=scoreHistory,proto3" json:"scoreHistory,omitempty"`
	FormatsWithUpcomingChange []string               `protobuf:"bytes,4,rep,name=formatsWithUpcomingChange,proto3" json:"formatsWithUpcomingChange,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CardScore) Reset() {
	*x = CardScore{}
	mi := &file_ygo_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardScore) ProtoMessage() {}

func (x *CardScore) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardScore.ProtoReflect.Descriptor instead.
func (*CardScore) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{14}
}

func (x *CardScore) GetCurrentScoreByFormat() map[string]uint32 {
	if x != nil {
		return x.CurrentScoreByFormat
	}
	return nil
}

func (x *CardScore) GetUniqueFormats() []string {
	if x != nil {
		return x.UniqueFormats
	}
	return nil
}

func (x *CardScore) GetScoreHistory() []*ScoreInstance {
	if x != nil {
		return x.ScoreHistory
	}
	return nil
}

func (x *CardScore) GetFormatsWithUpcomingChange() []string {
	if x != nil {
		return x.FormatsWithUpcomingChange
	}
	return nil
}

type CardScores struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardInfo         map[string]*CardScore  `protobuf:"bytes,1,rep,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UnknownResources []string               `protobuf:"bytes,2,rep,name=unknown_resources,json=unknownResources,proto3" json:"unknown_resources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardScores) Reset() {
	*x = CardScores{}
	mi := &file_ygo_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardScores) ProtoMessage() {}

func (x *CardScores) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardScores.ProtoReflect.Descriptor instead.
func (*CardScores) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{15}
}

func (x *CardScores) GetCardInfo() map[string]*CardScore {
	if x != nil {
		return x.CardInfo
	}
	return nil
}

func (x *CardScores) GetUnknownResources() []string {
	if x != nil {
		return x.UnknownResources
	}
	return nil
}

type ScoreInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	EffectiveDate string                 `protobuf:"bytes,2,opt,name=effectiveDate,proto3" json:"effectiveDate,omitempty"`
	Score         uint32                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreInstance) Reset() {
	*x = ScoreInstance{}
	mi := &file_ygo_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreInstance) ProtoMessage() {}

func (x *ScoreInstance) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreInstance.ProtoReflect.Descriptor instead.
func (*ScoreInstance) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{16}
}

func (x *ScoreInstance) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScoreInstance) GetEffectiveDate() string {
	if x != nil {
		return x.EffectiveDate
	}
	return ""
}

func (x *ScoreInstance) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_ygo_service_proto protoreflect.FileDescriptor

const file_ygo_service_proto_rawDesc = "" +
	"\n" +
	"\x11ygo_service.proto\x12\x03ygo\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\n" +
	"CardColors\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.ygo.CardColors.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x1c\n" +
	"\n" +
	"ResourceID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x1f\n" +
	"\vResourceIDs\x12\x10\n" +
	"\x03IDs\x18\x01 \x03(\tR\x03IDs\"%\n" +
	"\rResourceNames\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"0\n" +
	"\n" +
	"SearchTerm\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\")\n" +
	"\tArchetype\x12\x1c\n" +
	"\tarchetype\x18\x01 \x01(\tR\tarchetype\"9\n" +
	"\vBlackListed\x12*\n" +
	"\x11black_listed_refs\x18\x01 \x03(\tR\x0fblackListedRefs\"\xa5\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tattribute\x18\x04 \x01(\tR\tattribute\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\x12?\n" +
	"\fmonster_type\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vmonsterType\x124\n" +
	"\x06attack\x18\a \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06attack\x126\n" +
	"\adefense\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\adefense\"\xb3\x01\n" +
	"\x05Cards\x125\n" +
	"\tcard_info\x18\x01 \x03(\v2\x18.ygo.Cards.CardInfoEntryR\bcardInfo\x12+\n" +
	"\x11unknown_resources\x18\x02 \x03(\tR\x10unknownResources\x1aF\n" +
	"\rCardInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.ygo.CardR\x05value:\x028\x01\"+\n" +
	"\bCardList\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\"\xfa\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\asubType\x18\x05 \x01(\tR\asubType\x12 \n" +
	"\vreleaseDate\x18\x06 \x01(\tR\vreleaseDate\x12\x1e\n" +
	"\n" +
	"totalItems\x18\a \x01(\rR\n" +
	"totalItems\x12&\n" +
	"\x05items\x18\b \x03(\v2\x10.ygo.ProductItemR\x05items\x12T\n" +
	"\x12rarityDistribution\x18\t \x03(\v2$.ygo.Product.RarityDistributionEntryR\x12rarityDistribution\x1aE\n" +
	"\x17RarityDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"d\n" +
	"\vProductItem\x12\x1d\n" +
	"\x04card\x18\x01 \x01(\v2\t.ygo.CardR\x04card\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1a\n" +
	"\brarities\x18\x03 \x03(\tR\brarities\"\xbc\x01\n" +
	"\x0eProductSummary\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\asubType\x18\x05 \x01(\tR\asubType\x12 \n" +
	"\vreleaseDate\x18\x06 \x01(\tR\vreleaseDate\x12\x1e\n" +
	"\n" +
	"totalItems\x18\a \x01(\rR\n" +
	"totalItems\"\xc2\x01\n" +
	"\bProducts\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.ygo.Products.ProductsEntryR\bproducts\x12+\n" +
	"\x11unknown_resources\x18\x02 \x03(\tR\x10unknownResources\x1aP\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.ygo.ProductSummaryR\x05value:\x028\x01\"\xce\x02\n" +
	"\tCardScore\x12\\\n" +
	"\x14currentScoreByFormat\x18\x01 \x03(\v2(.ygo.CardScore.CurrentScoreByFormatEntryR\x14currentScoreByFormat\x12$\n" +
	"\runiqueFormats\x18\x02 \x03(\tR\runiqueFormats\x126\n" +
	"\fscoreHistory\x18\x03 \x03(\v2\x12.ygo.ScoreInstanceR\fscoreHistory\x12<\n" +
	"\x19formatsWithUpcomingChange\x18\x04 \x03(\tR\x19formatsWithUpcomingChange\x1aG\n" +
	"\x19CurrentScoreByFormatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xc2\x01\n" +
	"\n" +
	"CardScores\x12:\n" +
	"\tcard_info\x18\x01 \x03(\v2\x1d.ygo.CardScores.CardInfoEntryR\bcardInfo\x12+\n" +
	"\x11unknown_resources\x18\x02 \x03(\tR\x10unknownResources\x1aK\n" +
	"\rCardInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.ygo.CardScoreR\x05value:\x028\x01\"c\n" +
	"\rScoreInstance\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12$\n" +
	"\reffectiveDate\x18\x02 \x01(\tR\reffectiveDate\x12\x14\n" +
	"\x05score\x18\x03 \x01(\rR\x05score2\x8c\x04\n" +
	"\vCardService\x128\n" +
	"\rGetCardColors\x12\x16.google.protobuf.Empty\x1a\x0f.ygo.CardColors\x12)\n" +
	"\vGetCardByID\x12\x0f.ygo.ResourceID\x1a\t.ygo.Card\x12,\n" +
	"\fGetCardsByID\x12\x10.ygo.ResourceIDs\x1a\n" +
	".ygo.Cards\x120\n" +
	"\x0eGetCardsByName\x12\x12.ygo.ResourceNames\x1a\n" +
	".ygo.Cards\x12D\n" +
	"\x1fGetCardsReferencingNameInEffect\x12\x12.ygo.ResourceNames\x1a\r.ygo.CardList\x12@\n" +
	"\x1fGetArchetypalCardsUsingCardName\x12\x0e.ygo.Archetype\x1a\r.ygo.CardList\x12@\n" +
	"\x1fGetExplicitArchetypalInclusions\x12\x0e.ygo.Archetype\x1a\r.ygo.CardList\x12@\n" +
	"\x1fGetExplicitArchetypalExclusions\x12\x0e.ygo.Archetype\x1a\r.ygo.CardList\x12,\n" +
	"\rGetRandomCard\x12\x10.ygo.BlackListed\x1a\t.ygo.Card2\xc0\x01\n" +
	"\x0eProductService\x124\n" +
	"\x13GetCardsByProductID\x12\x0f.ygo.ResourceID\x1a\f.ygo.Product\x12=\n" +
	"\x15GetProductSummaryByID\x12\x0f.ygo.ResourceID\x1a\x13.ygo.ProductSummary\x129\n" +
	"\x16GetProductsSummaryByID\x12\x10.ygo.ResourceIDs\x1a\r.ygo.Products2|\n" +
	"\fScoreService\x123\n" +
	"\x10GetCardScoreByID\x12\x0f.ygo.ResourceID\x1a\x0e.ygo.CardScore\x127\n" +
	"\x12GetCardScoresByIDs\x12\x10.ygo.ResourceIDs\x1a\x0f.ygo.CardScoresB\x06Z\x04/ygob\x06proto3"

var (
	file_ygo_service_proto_rawDescOnce sync.Once
	file_ygo_service_proto_rawDescData []byte
)

func file_ygo_service_proto_rawDescGZIP() []byte {
	file_ygo_service_proto_rawDescOnce.Do(func() {
		file_ygo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)))
	})
	return file_ygo_service_proto_rawDescData
}

var file_ygo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ygo_service_proto_goTypes = []any{
	(*CardColors)(nil),             // 0: ygo.CardColors
	(*ResourceID)(nil),             // 1: ygo.ResourceID
	(*ResourceIDs)(nil),            // 2: ygo.ResourceIDs
	(*ResourceNames)(nil),          // 3: ygo.ResourceNames
	(*SearchTerm)(nil),             // 4: ygo.SearchTerm
	(*Archetype)(nil),              // 5: ygo.Archetype
	(*BlackListed)(nil),            // 6: ygo.BlackListed
	(*Card)(nil),                   // 7: ygo.Card
	(*Cards)(nil),                  // 8: ygo.Cards
	(*CardList)(nil),               // 9: ygo.CardList
	(*Product)(nil),                // 10: ygo.Product
	(*ProductItem)(nil),            // 11: ygo.ProductItem
	(*ProductSummary)(nil),         // 12: ygo.ProductSummary
	(*Products)(nil),               // 13: ygo.Products
	(*CardScore)(nil),              // 14: ygo.CardScore
	(*CardScores)(nil),             // 15: ygo.CardScores
	(*ScoreInstance)(nil),          // 16: ygo.ScoreInstance
	nil,                            // 17: ygo.CardColors.ValuesEntry
	nil,                            // 18: ygo.Cards.CardInfoEntry
	nil,                            // 19: ygo.Product.RarityDistributionEntry
	nil,                            // 20: ygo.Products.ProductsEntry
	nil,                            // 21: ygo.CardScore.CurrentScoreByFormatEntry
	nil,                            // 22: ygo.CardScores.CardInfoEntry
	(*wrapperspb.StringValue)(nil), // 23: google.protobuf.StringValue
	(*wrapperspb.UInt32Value)(nil), // 24: google.protobuf.UInt32Value
	(*emptypb.Empty)(nil),          // 25: google.protobuf.Empty
}
var file_ygo_service_proto_depIdxs = []int32{
	17, // 0: ygo.CardColors.values:type_name -> ygo.CardColors.ValuesEntry
	23, // 1: ygo.Card.monster_type:type_name -> google.protobuf.StringValue
	24, // 2: ygo.Card.attack:type_name -> google.protobuf.UInt32Value
	24, // 3: ygo.Card.defense:type_name -> google.protobuf.UInt32Value
	18, // 4: ygo.Cards.card_info:type_name -> ygo.Cards.CardInfoEntry
	7,  // 5: ygo.CardList.cards:type_name -> ygo.Card
	11, // 6: ygo.Product.items:type_name -> ygo.ProductItem
	19, // 7: ygo.Product.rarityDistribution:type_name -> ygo.Product.RarityDistributionEntry
	7,  // 8: ygo.ProductItem.card:type_name -> ygo.Card
	20, // 9: ygo.Products.products:type_name -> ygo.Products.ProductsEntry
	21, // 10: ygo.CardScore.currentScoreByFormat:type_name -> ygo.CardScore.CurrentScoreByFormatEntry
	16, // 11: ygo.CardScore.scoreHistory:type_name -> ygo.ScoreInstance
	22, // 12: ygo.CardScores.card_info:type_name -> ygo.CardScores.CardInfoEntry
	7,  // 13: ygo.Cards.CardInfoEntry.value:type_name -> ygo.Card
	12, // 14: ygo.Products.ProductsEntry.value:type_name -> ygo.ProductSummary
	14, // 15: ygo.CardScores.CardInfoEntry.value:type_name -> ygo.CardScore
	25, // 16: ygo.CardService.GetCardColors:input_type -> google.protobuf.Empty
	1,  // 17: ygo.CardService.GetCardByID:input_type -> ygo.ResourceID
	2,  // 18: ygo.CardService.GetCardsByID:input_type -> ygo.ResourceIDs
	3,  // 19: ygo.CardService.GetCardsByName:input_type -> ygo.ResourceNames
	3,  // 20: ygo.CardService.GetCardsReferencingNameInEffect:input_type -> ygo.ResourceNames
	5,  // 21: ygo.CardService.GetArchetypalCardsUsingCardName:input_type -> ygo.Archetype
	5,  // 22: ygo.CardService.GetExplicitArchetypalInclusions:input_type -> ygo.Archetype
	5,  // 23: ygo.CardService.GetExplicitArchetypalExclusions:input_type -> ygo.Archetype
	6,  // 24: ygo.CardService.GetRandomCard:input_type -> ygo.BlackListed
	1,  // 25: ygo.ProductService.GetCardsByProductID:input_type -> ygo.ResourceID
	1,  // 26: ygo.ProductService.GetProductSummaryByID:input_type -> ygo.ResourceID
	2,  // 27: ygo.ProductService.GetProductsSummaryByID:input_type -> ygo.ResourceIDs
	1,  // 28: ygo.ScoreService.GetCardScoreByID:input_type -> ygo.ResourceID
	2,  // 29: ygo.ScoreService.GetCardScoresByIDs:input_type -> ygo.ResourceIDs
	0,  // 30: ygo.CardService.GetCardColors:output_type -> ygo.CardColors
	7,  // 31: ygo.CardService.GetCardByID:output_type -> ygo.Card
	8,  // 32: ygo.CardService.GetCardsByID:output_type -> ygo.Cards
	8,  // 33: ygo.CardService.GetCardsByName:output_type -> ygo.Cards
	9,  // 34: ygo.CardService.GetCardsReferencingNameInEffect:output_type -> ygo.CardList
	9,  // 35: ygo.CardService.GetArchetypalCardsUsingCardName:output_type -> ygo.CardList
	9,  // 36: ygo.CardService.GetExplicitArchetypalInclusions:output_type -> ygo.CardList
	9,  // 37: ygo.CardService.GetExplicitArchetypalExclusions:output_type -> ygo.CardList
	7,  // 38: ygo.CardService.GetRandomCard:output_type -> ygo.Card
	10, // 39: ygo.ProductService.GetCardsByProductID:output_type -> ygo.Product
	12, // 40: ygo.ProductService.GetProductSummaryByID:output_type -> ygo.ProductSummary
	13, // 41: ygo.ProductService.GetProductsSummaryByID:output_type -> ygo.Products
	14, // 42: ygo.ScoreService.GetCardScoreByID:output_type -> ygo.CardScore
	15, // 43: ygo.ScoreService.GetCardScoresByIDs:output_type -> ygo.CardScores
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ygo_service_proto_init() }
func file_ygo_service_proto_init() {
	if File_ygo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ygo_service_proto_goTypes,
		DependencyIndexes: file_ygo_service_proto_depIdxs,
		MessageInfos:      file_ygo_service_proto_msgTypes,
	}.Build()
	File_ygo_service_proto = out.File
	file_ygo_service_proto_goTypes = nil
	file_ygo_service_proto_depIdxs = nil
}
