// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ygo_service.proto

package ygo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCardColorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardColorsRequest) Reset() {
	*x = GetCardColorsRequest{}
	mi := &file_ygo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardColorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardColorsRequest) ProtoMessage() {}

func (x *GetCardColorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardColorsRequest.ProtoReflect.Descriptor instead.
func (*GetCardColorsRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{0}
}

type GetCardColorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]uint32      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardColorsResponse) Reset() {
	*x = GetCardColorsResponse{}
	mi := &file_ygo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardColorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardColorsResponse) ProtoMessage() {}

func (x *GetCardColorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardColorsResponse.ProtoReflect.Descriptor instead.
func (*GetCardColorsResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardColorsResponse) GetValues() map[string]uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetCardByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *ResourceID            `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByIDRequest) Reset() {
	*x = GetCardByIDRequest{}
	mi := &file_ygo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByIDRequest) ProtoMessage() {}

func (x *GetCardByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCardByIDRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardByIDRequest) GetSubject() *ResourceID {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetCardByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardByIDResponse) Reset() {
	*x = GetCardByIDResponse{}
	mi := &file_ygo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardByIDResponse) ProtoMessage() {}

func (x *GetCardByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCardByIDResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardByIDResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      *ResourceIDs           `protobuf:"bytes,1,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByIDRequest) Reset() {
	*x = GetCardsByIDRequest{}
	mi := &file_ygo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByIDRequest) ProtoMessage() {}

func (x *GetCardsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCardsByIDRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardsByIDRequest) GetSubjects() *ResourceIDs {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type GetCardsByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         *Cards                 `protobuf:"bytes,1,opt,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByIDResponse) Reset() {
	*x = GetCardsByIDResponse{}
	mi := &file_ygo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByIDResponse) ProtoMessage() {}

func (x *GetCardsByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCardsByIDResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCardsByIDResponse) GetCards() *Cards {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetCardsByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      *ResourceNames         `protobuf:"bytes,1,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByNameRequest) Reset() {
	*x = GetCardsByNameRequest{}
	mi := &file_ygo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByNameRequest) ProtoMessage() {}

func (x *GetCardsByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCardsByNameRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCardsByNameRequest) GetSubjects() *ResourceNames {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type GetCardsByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         *Cards                 `protobuf:"bytes,1,opt,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByNameResponse) Reset() {
	*x = GetCardsByNameResponse{}
	mi := &file_ygo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByNameResponse) ProtoMessage() {}

func (x *GetCardsByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByNameResponse.ProtoReflect.Descriptor instead.
func (*GetCardsByNameResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetCardsByNameResponse) GetCards() *Cards {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetCardsReferencingNameInEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      *ResourceNames         `protobuf:"bytes,1,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsReferencingNameInEffectRequest) Reset() {
	*x = GetCardsReferencingNameInEffectRequest{}
	mi := &file_ygo_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsReferencingNameInEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsReferencingNameInEffectRequest) ProtoMessage() {}

func (x *GetCardsReferencingNameInEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsReferencingNameInEffectRequest.ProtoReflect.Descriptor instead.
func (*GetCardsReferencingNameInEffectRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetCardsReferencingNameInEffectRequest) GetSubjects() *ResourceNames {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type GetCardsReferencingNameInEffectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsReferencingNameInEffectResponse) Reset() {
	*x = GetCardsReferencingNameInEffectResponse{}
	mi := &file_ygo_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsReferencingNameInEffectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsReferencingNameInEffectResponse) ProtoMessage() {}

func (x *GetCardsReferencingNameInEffectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsReferencingNameInEffectResponse.ProtoReflect.Descriptor instead.
func (*GetCardsReferencingNameInEffectResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCardsReferencingNameInEffectResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetArchetypalCardsUsingCardNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Archetype             `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArchetypalCardsUsingCardNameRequest) Reset() {
	*x = GetArchetypalCardsUsingCardNameRequest{}
	mi := &file_ygo_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchetypalCardsUsingCardNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypalCardsUsingCardNameRequest) ProtoMessage() {}

func (x *GetArchetypalCardsUsingCardNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypalCardsUsingCardNameRequest.ProtoReflect.Descriptor instead.
func (*GetArchetypalCardsUsingCardNameRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetArchetypalCardsUsingCardNameRequest) GetSubject() *Archetype {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetArchetypalCardsUsingCardNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArchetypalCardsUsingCardNameResponse) Reset() {
	*x = GetArchetypalCardsUsingCardNameResponse{}
	mi := &file_ygo_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchetypalCardsUsingCardNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchetypalCardsUsingCardNameResponse) ProtoMessage() {}

func (x *GetArchetypalCardsUsingCardNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchetypalCardsUsingCardNameResponse.ProtoReflect.Descriptor instead.
func (*GetArchetypalCardsUsingCardNameResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetArchetypalCardsUsingCardNameResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetExplicitArchetypalInclusionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Archetype             `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplicitArchetypalInclusionsRequest) Reset() {
	*x = GetExplicitArchetypalInclusionsRequest{}
	mi := &file_ygo_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplicitArchetypalInclusionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplicitArchetypalInclusionsRequest) ProtoMessage() {}

func (x *GetExplicitArchetypalInclusionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplicitArchetypalInclusionsRequest.ProtoReflect.Descriptor instead.
func (*GetExplicitArchetypalInclusionsRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetExplicitArchetypalInclusionsRequest) GetSubject() *Archetype {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetExplicitArchetypalInclusionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplicitArchetypalInclusionsResponse) Reset() {
	*x = GetExplicitArchetypalInclusionsResponse{}
	mi := &file_ygo_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplicitArchetypalInclusionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplicitArchetypalInclusionsResponse) ProtoMessage() {}

func (x *GetExplicitArchetypalInclusionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplicitArchetypalInclusionsResponse.ProtoReflect.Descriptor instead.
func (*GetExplicitArchetypalInclusionsResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetExplicitArchetypalInclusionsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetExplicitArchetypalExclusionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *Archetype             `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplicitArchetypalExclusionsRequest) Reset() {
	*x = GetExplicitArchetypalExclusionsRequest{}
	mi := &file_ygo_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplicitArchetypalExclusionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplicitArchetypalExclusionsRequest) ProtoMessage() {}

func (x *GetExplicitArchetypalExclusionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplicitArchetypalExclusionsRequest.ProtoReflect.Descriptor instead.
func (*GetExplicitArchetypalExclusionsRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetExplicitArchetypalExclusionsRequest) GetSubject() *Archetype {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetExplicitArchetypalExclusionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExplicitArchetypalExclusionsResponse) Reset() {
	*x = GetExplicitArchetypalExclusionsResponse{}
	mi := &file_ygo_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExplicitArchetypalExclusionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplicitArchetypalExclusionsResponse) ProtoMessage() {}

func (x *GetExplicitArchetypalExclusionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplicitArchetypalExclusionsResponse.ProtoReflect.Descriptor instead.
func (*GetExplicitArchetypalExclusionsResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetExplicitArchetypalExclusionsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GetRandomCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blacklist     *BlackListed           `protobuf:"bytes,1,opt,name=blacklist,proto3" json:"blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomCardRequest) Reset() {
	*x = GetRandomCardRequest{}
	mi := &file_ygo_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomCardRequest) ProtoMessage() {}

func (x *GetRandomCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomCardRequest.ProtoReflect.Descriptor instead.
func (*GetRandomCardRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetRandomCardRequest) GetBlacklist() *BlackListed {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

type GetRandomCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomCardResponse) Reset() {
	*x = GetRandomCardResponse{}
	mi := &file_ygo_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomCardResponse) ProtoMessage() {}

func (x *GetRandomCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomCardResponse.ProtoReflect.Descriptor instead.
func (*GetRandomCardResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetRandomCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardsByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *ResourceID            `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByProductIDRequest) Reset() {
	*x = GetCardsByProductIDRequest{}
	mi := &file_ygo_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByProductIDRequest) ProtoMessage() {}

func (x *GetCardsByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetCardsByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetCardsByProductIDRequest) GetSubject() *ResourceID {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetCardsByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByProductIDResponse) Reset() {
	*x = GetCardsByProductIDResponse{}
	mi := &file_ygo_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByProductIDResponse) ProtoMessage() {}

func (x *GetCardsByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetCardsByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetCardsByProductIDResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductSummaryByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *ResourceID            `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductSummaryByIDRequest) Reset() {
	*x = GetProductSummaryByIDRequest{}
	mi := &file_ygo_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSummaryByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSummaryByIDRequest) ProtoMessage() {}

func (x *GetProductSummaryByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSummaryByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductSummaryByIDRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetProductSummaryByIDRequest) GetSubject() *ResourceID {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetProductSummaryByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductSummary *ProductSummary        `protobuf:"bytes,1,opt,name=product_summary,json=productSummary,proto3" json:"product_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductSummaryByIDResponse) Reset() {
	*x = GetProductSummaryByIDResponse{}
	mi := &file_ygo_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSummaryByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSummaryByIDResponse) ProtoMessage() {}

func (x *GetProductSummaryByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSummaryByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductSummaryByIDResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetProductSummaryByIDResponse) GetProductSummary() *ProductSummary {
	if x != nil {
		return x.ProductSummary
	}
	return nil
}

type GetProductsSummaryByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      *ResourceIDs           `protobuf:"bytes,1,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsSummaryByIDRequest) Reset() {
	*x = GetProductsSummaryByIDRequest{}
	mi := &file_ygo_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsSummaryByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsSummaryByIDRequest) ProtoMessage() {}

func (x *GetProductsSummaryByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsSummaryByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductsSummaryByIDRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetProductsSummaryByIDRequest) GetSubjects() *ResourceIDs {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type GetProductsSummaryByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsSummaryByIDResponse) Reset() {
	*x = GetProductsSummaryByIDResponse{}
	mi := &file_ygo_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsSummaryByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsSummaryByIDResponse) ProtoMessage() {}

func (x *GetProductsSummaryByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsSummaryByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductsSummaryByIDResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetProductsSummaryByIDResponse) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductsReleasedSameDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReleasedSameDayRequest) Reset() {
	*x = GetProductsReleasedSameDayRequest{}
	mi := &file_ygo_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReleasedSameDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReleasedSameDayRequest) ProtoMessage() {}

func (x *GetProductsReleasedSameDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReleasedSameDayRequest.ProtoReflect.Descriptor instead.
func (*GetProductsReleasedSameDayRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetProductsReleasedSameDayRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetProductsReleasedSameDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       []*ProductSummary      `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReleasedSameDayResponse) Reset() {
	*x = GetProductsReleasedSameDayResponse{}
	mi := &file_ygo_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReleasedSameDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReleasedSameDayResponse) ProtoMessage() {}

func (x *GetProductsReleasedSameDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReleasedSameDayResponse.ProtoReflect.Descriptor instead.
func (*GetProductsReleasedSameDayResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetProductsReleasedSameDayResponse) GetProduct() []*ProductSummary {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetCardScoresByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subjects      *ResourceIDs           `protobuf:"bytes,1,opt,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardScoresByIDsRequest) Reset() {
	*x = GetCardScoresByIDsRequest{}
	mi := &file_ygo_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardScoresByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardScoresByIDsRequest) ProtoMessage() {}

func (x *GetCardScoresByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardScoresByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetCardScoresByIDsRequest) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetCardScoresByIDsRequest) GetSubjects() *ResourceIDs {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type GetCardScoresByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        *CardScores            `protobuf:"bytes,1,opt,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardScoresByIDsResponse) Reset() {
	*x = GetCardScoresByIDsResponse{}
	mi := &file_ygo_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardScoresByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardScoresByIDsResponse) ProtoMessage() {}

func (x *GetCardScoresByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ygo_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardScoresByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetCardScoresByIDsResponse) Descriptor() ([]byte, []int) {
	return file_ygo_service_proto_rawDescGZIP(), []int{27}
}

func (x *GetCardScoresByIDsResponse) GetScores() *CardScores {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_ygo_service_proto protoreflect.FileDescriptor

const file_ygo_service_proto_rawDesc = "" +
	"\n" +
	"\x11ygo_service.proto\x12\x03ygo\x1a\fcommon.proto\"\x16\n" +
	"\x14GetCardColorsRequest\"\x92\x01\n" +
	"\x15GetCardColorsResponse\x12>\n" +
	"\x06values\x18\x01 \x03(\v2&.ygo.GetCardColorsResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"?\n" +
	"\x12GetCardByIDRequest\x12)\n" +
	"\asubject\x18\x01 \x01(\v2\x0f.ygo.ResourceIDR\asubject\"4\n" +
	"\x13GetCardByIDResponse\x12\x1d\n" +
	"\x04card\x18\x01 \x01(\v2\t.ygo.CardR\x04card\"C\n" +
	"\x13GetCardsByIDRequest\x12,\n" +
	"\bsubjects\x18\x01 \x01(\v2\x10.ygo.ResourceIDsR\bsubjects\"8\n" +
	"\x14GetCardsByIDResponse\x12 \n" +
	"\x05cards\x18\x01 \x01(\v2\n" +
	".ygo.CardsR\x05cards\"G\n" +
	"\x15GetCardsByNameRequest\x12.\n" +
	"\bsubjects\x18\x01 \x01(\v2\x12.ygo.ResourceNamesR\bsubjects\":\n" +
	"\x16GetCardsByNameResponse\x12 \n" +
	"\x05cards\x18\x01 \x01(\v2\n" +
	".ygo.CardsR\x05cards\"X\n" +
	"&GetCardsReferencingNameInEffectRequest\x12.\n" +
	"\bsubjects\x18\x01 \x01(\v2\x12.ygo.ResourceNamesR\bsubjects\"J\n" +
	"'GetCardsReferencingNameInEffectResponse\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\"R\n" +
	"&GetArchetypalCardsUsingCardNameRequest\x12(\n" +
	"\asubject\x18\x01 \x01(\v2\x0e.ygo.ArchetypeR\asubject\"J\n" +
	"'GetArchetypalCardsUsingCardNameResponse\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\"R\n" +
	"&GetExplicitArchetypalInclusionsRequest\x12(\n" +
	"\asubject\x18\x01 \x01(\v2\x0e.ygo.ArchetypeR\asubject\"J\n" +
	"'GetExplicitArchetypalInclusionsResponse\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\"R\n" +
	"&GetExplicitArchetypalExclusionsRequest\x12(\n" +
	"\asubject\x18\x01 \x01(\v2\x0e.ygo.ArchetypeR\asubject\"J\n" +
	"'GetExplicitArchetypalExclusionsResponse\x12\x1f\n" +
	"\x05cards\x18\x01 \x03(\v2\t.ygo.CardR\x05cards\"F\n" +
	"\x14GetRandomCardRequest\x12.\n" +
	"\tblacklist\x18\x01 \x01(\v2\x10.ygo.BlackListedR\tblacklist\"6\n" +
	"\x15GetRandomCardResponse\x12\x1d\n" +
	"\x04card\x18\x01 \x01(\v2\t.ygo.CardR\x04card\"G\n" +
	"\x1aGetCardsByProductIDRequest\x12)\n" +
	"\asubject\x18\x01 \x01(\v2\x0f.ygo.ResourceIDR\asubject\"E\n" +
	"\x1bGetCardsByProductIDResponse\x12&\n" +
	"\aproduct\x18\x01 \x01(\v2\f.ygo.ProductR\aproduct\"I\n" +
	"\x1cGetProductSummaryByIDRequest\x12)\n" +
	"\asubject\x18\x01 \x01(\v2\x0f.ygo.ResourceIDR\asubject\"]\n" +
	"\x1dGetProductSummaryByIDResponse\x12<\n" +
	"\x0fproduct_summary\x18\x01 \x01(\v2\x13.ygo.ProductSummaryR\x0eproductSummary\"M\n" +
	"\x1dGetProductsSummaryByIDRequest\x12,\n" +
	"\bsubjects\x18\x01 \x01(\v2\x10.ygo.ResourceIDsR\bsubjects\"K\n" +
	"\x1eGetProductsSummaryByIDResponse\x12)\n" +
	"\bproducts\x18\x01 \x01(\v2\r.ygo.ProductsR\bproducts\"7\n" +
	"!GetProductsReleasedSameDayRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"S\n" +
	"\"GetProductsReleasedSameDayResponse\x12-\n" +
	"\aproduct\x18\x01 \x03(\v2\x13.ygo.ProductSummaryR\aproduct\"I\n" +
	"\x19GetCardScoresByIDsRequest\x12,\n" +
	"\bsubjects\x18\x01 \x01(\v2\x10.ygo.ResourceIDsR\bsubjects\"E\n" +
	"\x1aGetCardScoresByIDsResponse\x12'\n" +
	"\x06scores\x18\x01 \x01(\v2\x0f.ygo.CardScoresR\x06scores2\xe7\x06\n" +
	"\vCardService\x12F\n" +
	"\rGetCardColors\x12\x19.ygo.GetCardColorsRequest\x1a\x1a.ygo.GetCardColorsResponse\x12@\n" +
	"\vGetCardByID\x12\x17.ygo.GetCardByIDRequest\x1a\x18.ygo.GetCardByIDResponse\x12C\n" +
	"\fGetCardsByID\x12\x18.ygo.GetCardsByIDRequest\x1a\x19.ygo.GetCardsByIDResponse\x12I\n" +
	"\x0eGetCardsByName\x12\x1a.ygo.GetCardsByNameRequest\x1a\x1b.ygo.GetCardsByNameResponse\x12|\n" +
	"\x1fGetCardsReferencingNameInEffect\x12+.ygo.GetCardsReferencingNameInEffectRequest\x1a,.ygo.GetCardsReferencingNameInEffectResponse\x12|\n" +
	"\x1fGetArchetypalCardsUsingCardName\x12+.ygo.GetArchetypalCardsUsingCardNameRequest\x1a,.ygo.GetArchetypalCardsUsingCardNameResponse\x12|\n" +
	"\x1fGetExplicitArchetypalInclusions\x12+.ygo.GetExplicitArchetypalInclusionsRequest\x1a,.ygo.GetExplicitArchetypalInclusionsResponse\x12|\n" +
	"\x1fGetExplicitArchetypalExclusions\x12+.ygo.GetExplicitArchetypalExclusionsRequest\x1a,.ygo.GetExplicitArchetypalExclusionsResponse\x12F\n" +
	"\rGetRandomCard\x12\x19.ygo.GetRandomCardRequest\x1a\x1a.ygo.GetRandomCardResponse2\x9c\x03\n" +
	"\x0eProductService\x12X\n" +
	"\x13GetCardsByProductID\x12\x1f.ygo.GetCardsByProductIDRequest\x1a .ygo.GetCardsByProductIDResponse\x12^\n" +
	"\x15GetProductSummaryByID\x12!.ygo.GetProductSummaryByIDRequest\x1a\".ygo.GetProductSummaryByIDResponse\x12a\n" +
	"\x16GetProductsSummaryByID\x12\".ygo.GetProductsSummaryByIDRequest\x1a#.ygo.GetProductsSummaryByIDResponse\x12m\n" +
	"\x1aGetProductsReleasedSameDay\x12&.ygo.GetProductsReleasedSameDayRequest\x1a'.ygo.GetProductsReleasedSameDayResponse2^\n" +
	"\x16CardRestrictionService\x12D\n" +
	"\x1dGetEffectiveTimelineForFormat\x12\v.ygo.Format\x1a\x16.ygo.EffectiveTimeline2\xf2\x01\n" +
	"\fScoreService\x12V\n" +
	"\x18GetScoresByFormatAndDate\x12\x1d.ygo.RestrictedContentRequest\x1a\x1b.ygo.ScoresForFormatAndDate\x123\n" +
	"\x10GetCardScoreByID\x12\x0f.ygo.ResourceID\x1a\x0e.ygo.CardScore\x12U\n" +
	"\x12GetCardScoresByIDs\x12\x1e.ygo.GetCardScoresByIDsRequest\x1a\x1f.ygo.GetCardScoresByIDsResponseB\x06Z\x04/ygob\x06proto3"

var (
	file_ygo_service_proto_rawDescOnce sync.Once
	file_ygo_service_proto_rawDescData []byte
)

func file_ygo_service_proto_rawDescGZIP() []byte {
	file_ygo_service_proto_rawDescOnce.Do(func() {
		file_ygo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)))
	})
	return file_ygo_service_proto_rawDescData
}

var file_ygo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ygo_service_proto_goTypes = []any{
	(*GetCardColorsRequest)(nil),                    // 0: ygo.GetCardColorsRequest
	(*GetCardColorsResponse)(nil),                   // 1: ygo.GetCardColorsResponse
	(*GetCardByIDRequest)(nil),                      // 2: ygo.GetCardByIDRequest
	(*GetCardByIDResponse)(nil),                     // 3: ygo.GetCardByIDResponse
	(*GetCardsByIDRequest)(nil),                     // 4: ygo.GetCardsByIDRequest
	(*GetCardsByIDResponse)(nil),                    // 5: ygo.GetCardsByIDResponse
	(*GetCardsByNameRequest)(nil),                   // 6: ygo.GetCardsByNameRequest
	(*GetCardsByNameResponse)(nil),                  // 7: ygo.GetCardsByNameResponse
	(*GetCardsReferencingNameInEffectRequest)(nil),  // 8: ygo.GetCardsReferencingNameInEffectRequest
	(*GetCardsReferencingNameInEffectResponse)(nil), // 9: ygo.GetCardsReferencingNameInEffectResponse
	(*GetArchetypalCardsUsingCardNameRequest)(nil),  // 10: ygo.GetArchetypalCardsUsingCardNameRequest
	(*GetArchetypalCardsUsingCardNameResponse)(nil), // 11: ygo.GetArchetypalCardsUsingCardNameResponse
	(*GetExplicitArchetypalInclusionsRequest)(nil),  // 12: ygo.GetExplicitArchetypalInclusionsRequest
	(*GetExplicitArchetypalInclusionsResponse)(nil), // 13: ygo.GetExplicitArchetypalInclusionsResponse
	(*GetExplicitArchetypalExclusionsRequest)(nil),  // 14: ygo.GetExplicitArchetypalExclusionsRequest
	(*GetExplicitArchetypalExclusionsResponse)(nil), // 15: ygo.GetExplicitArchetypalExclusionsResponse
	(*GetRandomCardRequest)(nil),                    // 16: ygo.GetRandomCardRequest
	(*GetRandomCardResponse)(nil),                   // 17: ygo.GetRandomCardResponse
	(*GetCardsByProductIDRequest)(nil),              // 18: ygo.GetCardsByProductIDRequest
	(*GetCardsByProductIDResponse)(nil),             // 19: ygo.GetCardsByProductIDResponse
	(*GetProductSummaryByIDRequest)(nil),            // 20: ygo.GetProductSummaryByIDRequest
	(*GetProductSummaryByIDResponse)(nil),           // 21: ygo.GetProductSummaryByIDResponse
	(*GetProductsSummaryByIDRequest)(nil),           // 22: ygo.GetProductsSummaryByIDRequest
	(*GetProductsSummaryByIDResponse)(nil),          // 23: ygo.GetProductsSummaryByIDResponse
	(*GetProductsReleasedSameDayRequest)(nil),       // 24: ygo.GetProductsReleasedSameDayRequest
	(*GetProductsReleasedSameDayResponse)(nil),      // 25: ygo.GetProductsReleasedSameDayResponse
	(*GetCardScoresByIDsRequest)(nil),               // 26: ygo.GetCardScoresByIDsRequest
	(*GetCardScoresByIDsResponse)(nil),              // 27: ygo.GetCardScoresByIDsResponse
	nil,                                             // 28: ygo.GetCardColorsResponse.ValuesEntry
	(*ResourceID)(nil),                              // 29: ygo.ResourceID
	(*Card)(nil),                                    // 30: ygo.Card
	(*ResourceIDs)(nil),                             // 31: ygo.ResourceIDs
	(*Cards)(nil),                                   // 32: ygo.Cards
	(*ResourceNames)(nil),                           // 33: ygo.ResourceNames
	(*Archetype)(nil),                               // 34: ygo.Archetype
	(*BlackListed)(nil),                             // 35: ygo.BlackListed
	(*Product)(nil),                                 // 36: ygo.Product
	(*ProductSummary)(nil),                          // 37: ygo.ProductSummary
	(*Products)(nil),                                // 38: ygo.Products
	(*CardScores)(nil),                              // 39: ygo.CardScores
	(*Format)(nil),                                  // 40: ygo.Format
	(*RestrictedContentRequest)(nil),                // 41: ygo.RestrictedContentRequest
	(*EffectiveTimeline)(nil),                       // 42: ygo.EffectiveTimeline
	(*ScoresForFormatAndDate)(nil),                  // 43: ygo.ScoresForFormatAndDate
	(*CardScore)(nil),                               // 44: ygo.CardScore
}
var file_ygo_service_proto_depIdxs = []int32{
	28, // 0: ygo.GetCardColorsResponse.values:type_name -> ygo.GetCardColorsResponse.ValuesEntry
	29, // 1: ygo.GetCardByIDRequest.subject:type_name -> ygo.ResourceID
	30, // 2: ygo.GetCardByIDResponse.card:type_name -> ygo.Card
	31, // 3: ygo.GetCardsByIDRequest.subjects:type_name -> ygo.ResourceIDs
	32, // 4: ygo.GetCardsByIDResponse.cards:type_name -> ygo.Cards
	33, // 5: ygo.GetCardsByNameRequest.subjects:type_name -> ygo.ResourceNames
	32, // 6: ygo.GetCardsByNameResponse.cards:type_name -> ygo.Cards
	33, // 7: ygo.GetCardsReferencingNameInEffectRequest.subjects:type_name -> ygo.ResourceNames
	30, // 8: ygo.GetCardsReferencingNameInEffectResponse.cards:type_name -> ygo.Card
	34, // 9: ygo.GetArchetypalCardsUsingCardNameRequest.subject:type_name -> ygo.Archetype
	30, // 10: ygo.GetArchetypalCardsUsingCardNameResponse.cards:type_name -> ygo.Card
	34, // 11: ygo.GetExplicitArchetypalInclusionsRequest.subject:type_name -> ygo.Archetype
	30, // 12: ygo.GetExplicitArchetypalInclusionsResponse.cards:type_name -> ygo.Card
	34, // 13: ygo.GetExplicitArchetypalExclusionsRequest.subject:type_name -> ygo.Archetype
	30, // 14: ygo.GetExplicitArchetypalExclusionsResponse.cards:type_name -> ygo.Card
	35, // 15: ygo.GetRandomCardRequest.blacklist:type_name -> ygo.BlackListed
	30, // 16: ygo.GetRandomCardResponse.card:type_name -> ygo.Card
	29, // 17: ygo.GetCardsByProductIDRequest.subject:type_name -> ygo.ResourceID
	36, // 18: ygo.GetCardsByProductIDResponse.product:type_name -> ygo.Product
	29, // 19: ygo.GetProductSummaryByIDRequest.subject:type_name -> ygo.ResourceID
	37, // 20: ygo.GetProductSummaryByIDResponse.product_summary:type_name -> ygo.ProductSummary
	31, // 21: ygo.GetProductsSummaryByIDRequest.subjects:type_name -> ygo.ResourceIDs
	38, // 22: ygo.GetProductsSummaryByIDResponse.products:type_name -> ygo.Products
	37, // 23: ygo.GetProductsReleasedSameDayResponse.product:type_name -> ygo.ProductSummary
	31, // 24: ygo.GetCardScoresByIDsRequest.subjects:type_name -> ygo.ResourceIDs
	39, // 25: ygo.GetCardScoresByIDsResponse.scores:type_name -> ygo.CardScores
	0,  // 26: ygo.CardService.GetCardColors:input_type -> ygo.GetCardColorsRequest
	2,  // 27: ygo.CardService.GetCardByID:input_type -> ygo.GetCardByIDRequest
	4,  // 28: ygo.CardService.GetCardsByID:input_type -> ygo.GetCardsByIDRequest
	6,  // 29: ygo.CardService.GetCardsByName:input_type -> ygo.GetCardsByNameRequest
	8,  // 30: ygo.CardService.GetCardsReferencingNameInEffect:input_type -> ygo.GetCardsReferencingNameInEffectRequest
	10, // 31: ygo.CardService.GetArchetypalCardsUsingCardName:input_type -> ygo.GetArchetypalCardsUsingCardNameRequest
	12, // 32: ygo.CardService.GetExplicitArchetypalInclusions:input_type -> ygo.GetExplicitArchetypalInclusionsRequest
	14, // 33: ygo.CardService.GetExplicitArchetypalExclusions:input_type -> ygo.GetExplicitArchetypalExclusionsRequest
	16, // 34: ygo.CardService.GetRandomCard:input_type -> ygo.GetRandomCardRequest
	18, // 35: ygo.ProductService.GetCardsByProductID:input_type -> ygo.GetCardsByProductIDRequest
	20, // 36: ygo.ProductService.GetProductSummaryByID:input_type -> ygo.GetProductSummaryByIDRequest
	22, // 37: ygo.ProductService.GetProductsSummaryByID:input_type -> ygo.GetProductsSummaryByIDRequest
	24, // 38: ygo.ProductService.GetProductsReleasedSameDay:input_type -> ygo.GetProductsReleasedSameDayRequest
	40, // 39: ygo.CardRestrictionService.GetEffectiveTimelineForFormat:input_type -> ygo.Format
	41, // 40: ygo.ScoreService.GetScoresByFormatAndDate:input_type -> ygo.RestrictedContentRequest
	29, // 41: ygo.ScoreService.GetCardScoreByID:input_type -> ygo.ResourceID
	26, // 42: ygo.ScoreService.GetCardScoresByIDs:input_type -> ygo.GetCardScoresByIDsRequest
	1,  // 43: ygo.CardService.GetCardColors:output_type -> ygo.GetCardColorsResponse
	3,  // 44: ygo.CardService.GetCardByID:output_type -> ygo.GetCardByIDResponse
	5,  // 45: ygo.CardService.GetCardsByID:output_type -> ygo.GetCardsByIDResponse
	7,  // 46: ygo.CardService.GetCardsByName:output_type -> ygo.GetCardsByNameResponse
	9,  // 47: ygo.CardService.GetCardsReferencingNameInEffect:output_type -> ygo.GetCardsReferencingNameInEffectResponse
	11, // 48: ygo.CardService.GetArchetypalCardsUsingCardName:output_type -> ygo.GetArchetypalCardsUsingCardNameResponse
	13, // 49: ygo.CardService.GetExplicitArchetypalInclusions:output_type -> ygo.GetExplicitArchetypalInclusionsResponse
	15, // 50: ygo.CardService.GetExplicitArchetypalExclusions:output_type -> ygo.GetExplicitArchetypalExclusionsResponse
	17, // 51: ygo.CardService.GetRandomCard:output_type -> ygo.GetRandomCardResponse
	19, // 52: ygo.ProductService.GetCardsByProductID:output_type -> ygo.GetCardsByProductIDResponse
	21, // 53: ygo.ProductService.GetProductSummaryByID:output_type -> ygo.GetProductSummaryByIDResponse
	23, // 54: ygo.ProductService.GetProductsSummaryByID:output_type -> ygo.GetProductsSummaryByIDResponse
	25, // 55: ygo.ProductService.GetProductsReleasedSameDay:output_type -> ygo.GetProductsReleasedSameDayResponse
	42, // 56: ygo.CardRestrictionService.GetEffectiveTimelineForFormat:output_type -> ygo.EffectiveTimeline
	43, // 57: ygo.ScoreService.GetScoresByFormatAndDate:output_type -> ygo.ScoresForFormatAndDate
	44, // 58: ygo.ScoreService.GetCardScoreByID:output_type -> ygo.CardScore
	27, // 59: ygo.ScoreService.GetCardScoresByIDs:output_type -> ygo.GetCardScoresByIDsResponse
	43, // [43:60] is the sub-list for method output_type
	26, // [26:43] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_ygo_service_proto_init() }
func file_ygo_service_proto_init() {
	if File_ygo_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ygo_service_proto_rawDesc), len(file_ygo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_ygo_service_proto_goTypes,
		DependencyIndexes: file_ygo_service_proto_depIdxs,
		MessageInfos:      file_ygo_service_proto_msgTypes,
	}.Build()
	File_ygo_service_proto = out.File
	file_ygo_service_proto_goTypes = nil
	file_ygo_service_proto_depIdxs = nil
}
